<?php
/**
 * Entry point "sidebar" script registration and enqueue.
 *
 * This file will be copied to the assets output directory
 * with Webpack using wp-scripts build. The build command must
 * be run before this file will be available.
 *
 * This file must be included from the build output directory in a project.
 * and will be loaded from there.
 *
 * @package archiveless
 */

/**
 * Register the plugin entry point assets so that they can be enqueued.
 */
function archiveless_register_plugin_scripts(): void {
	/**
	 * Asset file generated by wp-scripts.
	 *
	 * @var array{dependencies: string[], version: string}|false $asset_file
	 */
	$asset_file = include __DIR__ . '/index.asset.php';

	if ( ! $asset_file ) {
		return;
	}

	// Register the sidebar script.
	wp_register_script(
		'archiveless-sidebar-js',
		plugins_url( 'index.js', __FILE__ ),
		$asset_file['dependencies'],
		$asset_file['version'],
		true
	);
	wp_set_script_translations( 'archiveless-sidebar-js', 'archiveless' );
}
add_action( 'init', 'archiveless_register_plugin_scripts' );

/**
 * Enqueue styles/scripts for the sidebar entry point.
 */
function archiveless_enqueue_plugin(): void {
	wp_enqueue_script( 'archiveless-sidebar-js' );
}
add_action( 'enqueue_block_assets', 'archiveless_enqueue_plugin' );
